#!/bin/bash
set -e

# Dependencies

brew install gh nvim stow fzf rg fd asdf tree-sitter zoxide

# Setup aerospace

brew install --cask nikitabobko/tap/aerospace;

defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer;
defaults write com.apple.dock expose-group-apps -bool true && killall Dock;

# Setup Ghostty

brew install --cask ghostty

# Symlink dotfiles

stow .;
