#!/bin/bash
set -e

# Dependencies

brew install gh nvim stow fzf rg fd asdf tree-sitter zoxide tmux tmuxinator

# MacOS settings

defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer;
defaults write com.apple.dock expose-group-apps -bool true && killall Dock;

# Other apps
brew install --cask nikitabobko/tap/aerospace;
brew install --cask obsidian
brew install --cask ghostty
brew install --cask keepingyouawake

# Symlink dotfiles

stow .;
